FROM node:20-alpine@sha256:fb4cd12c85ee03686f6af5362a0b0d56d50c58a04632e6c0fb8363f609372293 AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_DEV_MAILBOX_URL
ENV VITE_DEV_MAILBOX_URL=${VITE_DEV_MAILBOX_URL}
ARG VITE_SUPPORT_EMAIL=support@example.com
ENV VITE_SUPPORT_EMAIL=${VITE_SUPPORT_EMAIL}
RUN npm run build

FROM nginx:1.27-alpine@sha256:65645c7bb6a0661892a8b03b89d0743208a18dd2f3f17a54ef4b76fb8e2f2a10

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
